<?php
/*
* List down files generated by easy.py based on logged in user
* Author: Rajan Hossain
* Date: December 15, 2018
*/
session_start();
include("../components/header.php");
include("../global.config.php");
include("../Class/class.inc.php");
$con = new Config();

//If not logged in then redirect
$current_url = explode("/",$_SERVER['REQUEST_URI']);
$current_page = substr($current_url[3], 0, -4);

//if no session user id was not available, redirect to login
$user_id_session = 0;
if (!isset($_SESSION['user_id'])){
	$con->redirect("login.php?return_back_url=" . $current_page);
}else {
	//Store the session to name target directory for each user
	$user_id_session = $_SESSION["user_id"];
}

//Fetch data for user
$files = scandir("../AutomaticFiles/{$user_id_session}");
?>

<!--User area-->
<?php include("../components/menu.php");?>
<hr />
<div class="col-md-12">
<?php 
	echo "<h4>List of files: </h4>";
	foreach ($files as $key=>$val){
		if ($key > 2){
			echo $val;
			echo "<hr />";
		}
	}
?>
</div>
